---
- name: Install apache2
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install apache2 package without using apt module
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Intentionally failing task - attempt to install non-existent package
      ansible.builtin.package:
        name: this-package-does-not-exist-12345
        state: present
      ignore_errors: yes

    - name: Start and enable Apache service
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes
