all:
  hosts:
    web-week5:
      ansible_host: 192.168.1.130
  vars:
    ansible_user: nessie
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519-skylab
  children:
    web:
      hosts:
        web-week5:
          ansible_host: 192.168.1.130
 
