---
name: Week 5 CI/CD

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch:

jobs:

  lint_test:
    name: Lint test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test & lint tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest ansible ansible-lint yamllint

      - name: YAML lint
        run: yamllint .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform init (no backend)
        working-directory: terraform
        run: terraform init -backend=false

      - name: Terraform fmt
        working-directory: terraform
        run: terraform fmt -check -diff

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Ansible lint
        run: ansible-lint ansible/apache-playbook.yml

  security_scan:
    name: Security scan
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov on Terraform
        working-directory: terraform
        run: |
          checkov --directory . --framework terraform \
            --output cli --output junitxml \
            --output-file-path console,checkov-report.xml
        continue-on-error: true

      - name: Run Checkov on Ansible
        run: |
          checkov --directory ansible --framework ansible \
            --output cli
        continue-on-error: true

      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-scan-results
          path: terraform/checkov-report.xml

  deploy:
    name: Deploy ansible & terraform
    runs-on: self-hosted
    needs: [lint_test, security_scan]
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Run Ansible
        run: |
          ansible-playbook ansible/apache-playbook.yml
